name: CD

on:
  pull_request:
    types: [closed]
    branches: ["main"]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - name: SSH로 EC2에 접속하여 환경 변수 설정 및 코드 업데이트
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_ENV: ${{ secrets.APP_ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          envs: APP_ENV
          script: |
            cd /home/ubuntu/cicd-practice
            rm -rf .env
            git pull origin main
            echo "$APP_ENV" > .env
            cat .env

      - name: Gradle 빌드 및 애플리케이션 재시작
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ubuntu/cicd-practice
            ./gradlew clean build -Dspring.profiles.active=prod
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar -Dspring.profiles.active=prod build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
